java_test(
    name = "MainTest", 
    srcs = ["MainTest.java"],
    deps = [
        "//app2/src/main/java/com/ejemplo/app2:app2_lib",
        "@maven//:junit_junit",
        "@maven//:org_hamcrest_hamcrest_core",
    ],
)
